### ISSUE TITLE
Use list layout for topic and profiles search results.

### ISSUE THREAD

**Issue by jpeizer1** [OpenDevelopmentMekong/wp-odm_solr#141]
I like how the Topics show up in the Search ALL with the thumbnail to the side and text. I would suggest that the actual section for topics (15) on the left side also show the data this way (and the extent to which any image based information could be standardized to look like this in search would probably provide far better context for a user when they are returned in results). If I search for “rain” and all I get back is a picture with Rain and Snow or Disasters, etc.. the context is lost. I have to click and search around more for why this was returned.
 
![capture2](https://user-images.githubusercontent.com/16559612/27358369-51921cdc-55e4-11e7-8576-978ee6ac6290.JPG)

When I see this as a search result (below) – really its much clearer why it comes up and is more consistent with the rest of the text-based items as well. Maybe not as pretty but far more practical and useful I think.
 
![capture3](https://user-images.githubusercontent.com/16559612/27358377-59d23490-55e4-11e7-8e25-6cfd60fd7e0c.JPG)

![captureq](https://user-images.githubusercontent.com/16559612/27358378-5c0096e4-55e4-11e7-8029-7628b8630b77.JPG)

RGDS
 
JP

**Comment by acorbi** [comment]
@jpeizer1 let me formulate your request on my own words to:
1. make sure I understand what you mean (i believe so :wink: )
2. Clarify for the others in case they have some doubts
3. Ask some questions myself and ask everyone for feedback.

So this change request involves harmonizing the way the results are presented on the search page (but also on data page and eventually on archive pages? ). Currently Topics, Profiles and Maps are displayed using the so-called **grid layout** and, if we would implement your request, they should be displayed using the **list layout** (as news articles, announcements, site updates, etc...)

Now my questions:

- Would you suggest this change also on Archive pages such as http://pp.opendevelopmentmekong.net/topics/ or http://pp.opendevelopmentcambodia.net/profiles/ ?
- Would you suggest this change also for profiles and maps?

@prustar @gimmemochi @DBishton @Huyeng @ChandaraKhun @DragonVirus @thetaung2 what is your opinion on this?

**Comment by jpeizer1** [comment]
@acorbi  I dont think its necessary on  
http://pp.opendevelopmentmekong.net/topics/ or http://pp.opendevelopmentcambodia.net/profiles/ ?

But with search it's different - First it should be consistent in one comes back and if a user selects a data type in the side bar. Second, the reason users search is for context so the list method provides that. When they shown a grid with pictures. They still must drill down further to figure what behind the picture confirmed to their search request. The list format indicates that much more obviously.

For search I would suggest any data type that can show up in list form to represent its underlying data more clearly should be shown that way.

**Comment by Huyeng** [comment]
I agreed with @jpeizer1 for suggestion to update the layout of topic and profile as the list to be consistent with other on the same page. This is the same as ODC proposed for the All page. See this image:
![screenshot_4](https://user-images.githubusercontent.com/6613530/27668718-e4f21e86-5cac-11e7-8721-9ce5d2de820b.jpg)

**Comment by acorbi** [comment]
@jpeizer1 @Huyeng thanks, I will do the following change right now then:

- Use **list layout** for topic and profiles search results.

Also changing the name of this issue so it is consistent.
