### ISSUE TITLE
The dataset of Vietnam appeared on ODC search page

### ISSUE THREAD

**Issue by Huyeng** [OpenDevelopmentMekong/wp-odm_solr#156]
The Vietnamese dataset hosting on CKAN is showed up on ODC's English site, but it should not. 
<img width="1279" alt="screenshot at jun 28 21-30-27" src="https://user-images.githubusercontent.com/6613530/27642287-815e93ea-5c48-11e7-948a-c453082ea7aa.png">

See this page: https://opendevelopmentcambodia.net/?type=dataset&s=2011&taxonomy=all&metadata_created=all&sorting=score

You can produce the error:
- Keyword: "2011"
- Search
- on Dataset tab: you will see it.

**Comment by acorbi** [comment]
This issue has been already fixed on PP and will be solved once we roll-out the latest code base to PROD. This will happen once it has been agreed that the current codebase on PP is good to go live.

**Comment by acorbi** [comment]
Fixed now
