### ISSUE TITLE
Search: View detail of CKAN dataset doesn't work

### ISSUE THREAD

**Issue by Huyeng** [OpenDevelopmentMekong/wp-odm_solr#159]
When click on the title of dataset on result list, it will bring to dataset detail page, but no information of dataset. It seems like the url is not pointed correctly. 

Produce case: 
- Search any keyword on PP site
- Click any dataset of ckan on All tab or dataset tab
- Error
Testing url:
https://pp.opendevelopmentcambodia.net/?type=all&s=+Rice+production+response+and+technological+measures&taxonomy=all&metadata_created=all&sorting=score

**Comment by acorbi** [comment]
@Huyeng thanks for raising this. Im checking now
