### ISSUE TITLE
Search: Why the number news found on the search page is different on the Backend

### ISSUE THREAD

**Issue by Huyeng** [OpenDevelopmentMekong/wp-odm_solr#160]
Searching keyword: Aids
Result url: https://pp.opendevelopmentcambodia.net/?type=news-article&s=AIDS&taxonomy=all&metadata_created=all&sorting=score 

![screenshot_10](https://user-images.githubusercontent.com/6613530/27682940-97a448ba-5cee-11e7-80be-5720abf53bcd.jpg)

![screenshot_12](https://user-images.githubusercontent.com/6613530/27682975-b0710536-5cee-11e7-9458-e617fdd7d788.jpg)

**Comment by acorbi** [comment]
@Huyeng the search algorithms of WP are different than Solr's. Solr takes in consideration various combination of that word, similar words, synonyms, etc... That explains why those numbers are differnt. Closing this issue now, re-open if there is anything else you want to raise in this regard.

**Comment by Huyeng** [comment]
I think so, but I just asked to ensure that you the result of searching is correct as expected.
