### ISSUE TITLE
Search: All tab was hidden when the sort by is clicked

### ISSUE THREAD

**Issue by Huyeng** [OpenDevelopmentMekong/wp-odm_solr#164]
![screenshot_11](https://user-images.githubusercontent.com/6613530/27684105-b1c6f586-5cf2-11e7-964b-4bd34142f370.jpg)

https://pp.opendevelopmentcambodia.net/?type=profiles&s=AIDS+&taxonomy=all&metadata_created=all&sorting=metadata_created

**Comment by acorbi** [comment]
Fixed via Solr configuration
