### ISSUE TITLE
Search: Enhance the Announment layout on search result page 

### ISSUE THREAD

**Issue by Huyeng** [OpenDevelopmentMekong/wp-odm_solr#165]
Suggest to enhance the layout of the announcement like the screenshot by moving the download to the button as the dataset and remove the flag icons near by the download. see the image 
Note, update this layout should apply on the [Announcement ](https://pp.opendevelopmentcambodia.net/announcements) page as well.

![screenshot_13](https://user-images.githubusercontent.com/6613530/27684436-31807968-5cf4-11e7-8d18-08d28ed6bc17.jpg)

**Comment by acorbi** [comment]
@Huyeng Those announcements usually have 2 pdfs: one in english, one in khmer. How many [PDF] buttons would you then show? one or two? if we only show one, which would be the link assigned to it?

**Comment by Huyeng** [comment]
Just show only one pdf based on the site they are viewing. 
For example, in case the resources are available on two languages, so if the users are on the English site, then the pdf's link should be English. On Khmer site, it should be linked to the Khmer pdf. 

However, if there is only one language available, it should be showed in both site as did on the law tab:
https://pp.opendevelopmentcambodia.net/?type=laws_record&s=development&taxonomy=all&metadata_created=all&sorting=score&page=0

**Comment by acorbi** [comment]
sounds good to me

**Comment by acorbi** [comment]
moving to https://github.com/OpenDevelopmentMekong/wp-odm_theme/issues/1042
