### ISSUE TITLE
Search: Disable the authentication request on searching

### ISSUE THREAD

**Issue by Huyeng** [OpenDevelopmentMekong/wp-odm_solr#171]
I understood that the authentication is  used to prevent the access to the https://solr.opendevelopmentmekong.net. However, this will make the users feel annoy. 

I would like to suggest to change the approve for preventing this access. 

![screenshot_14](https://user-images.githubusercontent.com/6613530/27718572-f0a644e4-5d76-11e7-8f1f-5db386536865.jpg)

**Comment by acorbi** [comment]
Coordinated with proteus, se my message for the record:

>  Dear proteus team, can you please disable PWD protection for Solr PROD on the following url schemes?
https://solr.opendevelopmentmekong.net/solr/unified/select/*
https://solr.opendevelopmentmekong.net/solr/unified/suggestions/*
https://solr.opendevelopmentmekong.net/solr/unified/spell
https://solr.opendevelopmentmekong.net/solr/collection1/select/*
https://solr.opendevelopmentmekong.net/solr/collection1/suggestions/*
https://solr.opendevelopmentmekong.net/solr/collection1/spell/*
https://solr.opendevelopmentmekong.net/solr/wordpress_content/select/*
https://solr.opendevelopmentmekong.net/solr/wordpress_content/suggestions/*
https://solr.opendevelopmentmekong.net/solr/wordpress_content/spell/*
