### ISSUE TITLE
Data Sharing: Filter option on data page for different organisations

### ISSUE THREAD

**Issue by acorbi** [OpenDevelopmentMekong/wp-odm_solr#210]
Now that we have expanded the datasharing facility and have a number of organisations on board, we actually have a reporting requirement for MRLG that needs to specify how many of their partners have contributed to our platform and they need to report how many records they have contributed. To reduce the burden on us creating these reports, and providing to partners it would be great if we could have a filter option on the data page to filter by organisation. 

[filter.pdf](https://github.com/OpenDevelopmentMekong/wpckan/files/1371122/filter.pdf)

**Comment by acorbi** [comment]
In order to implement this request, following steps need to be undertaken:

- [ ] Implement dropdown-box for showing a list of organizations and letting the user filter after them. This UI element should only be presented when a CKAN record type is selected.

- [ ] Add the organization field to CKAN schema in order to be indexed and thus allowing the *filter by organization* queries to be effective

**Comment by prustar** [comment]
@acorbi - Yes **ALL** organisations should be filterable.

**Comment by acorbi** [comment]
@prustar This is now implemented on PP. See http://192.168.33.10/search/data/?type=dataset&taxonomy=all&sorting=score&query=&page=0

![screenshot from 2017-10-27 16-54-06](https://user-images.githubusercontent.com/384894/32110342-9510b816-bb37-11e7-9d67-13273d37f57f.png)
